<!-- End Navigation -->
<div class="container-fluid main-content">
    <!-- DataTables Example -->
    <div class="row">
        <div class="col-lg-12">
            <div class="widget-container fluid-height clearfix">
                <div class="widget-content padded clearfix">

                    <div class="heading">
                        <i class="icon-table"></i>奖品列表<br><br>

                        <label style="float:left; padding-top: 5px;">筛选活动：</label>
                        <div class="col-md-1">
                            <select id="activityId" class="form-control">
                                <option value="0" <?php echo $activityId == 0 ? 'selected' : ''?>>全部</option>
                                <option value="2" <?php echo $activityId == 2 ? 'selected' : ''?>>活动2</option>
                                <option value="3" <?php echo $activityId == 3 ? 'selected' : ''?>>活动3</option>
                                <option value="4" <?php echo $activityId == 4 ? 'selected' : ''?>>活动4</option>
                                <option value="6" <?php echo $activityId == 6 ? 'selected' : ''?>>活动6</option>
                            </select>
                        </div>
                    </div>

                    <table class="table table-striped">
                        <thead>
                        <th width="30%">
                            奖品名称
                        </th>
                        <th width="30%">
                            库存
                        </th>
                        <th>
                            操作
                        </th>
                        </thead>
                        <tbody>
                        <?php foreach($goodsList as $goods):?>
                            <tr>
                                <input type="hidden" id="goodsId" value="<?php echo $goods->id;?>">

                                <td>
                                    <a><?php echo $goods->name;?></a>
                                </td>
                                <td id="inventory"><?php echo $goods->inventory;?></td>
                                <td>
                                    <a class="edit">编辑数量</a>
                                    <div id="btn-box" style="display: none;">
                                        <a class="btn-ok">确认</a>
                                        <a class="btn-cancel">取消</a>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>




<script type="text/javascript">
    var origin = 0;

    $(function(){
        $('.edit').click(function(){
            $(this).hide();
            $(this).parent().find('#btn-box').show();
            var inventory = $(this).parent().parent().find('#inventory').html();
            origin = inventory;
            $(this).parent().parent().find('#inventory').html('<div class="col-md-7"><input id="input-inventory" class="form-control" type="text" value="'+inventory+'"></div>');
        });

        $('.btn-cancel').click(function(){
            hideEdit(this,origin);
        });

        $('.btn-ok').click(function(){
            var goodsId = $(this).parent().parent().parent().find('#goodsId').val();
            var inventory = $(this).parent().parent().parent().find('#input-inventory').val();
            var btn_cancel = $(this).parent().find('.btn-cancel');
            $.ajax({
                type: 'POST',
                url: '/qoros/adm/admin-goods/setGoodsInventory',
                data: {
                    goodsId:goodsId,
                    inventory:inventory
                },
                dataType: "json",
                success: function (data) {
                    if(data.status > 0){
                        showModal('系统提示',data.message);
                    } else  {
                        hideEdit(btn_cancel,inventory);
                    }
                }
            });
        });

        $("#activityId").change(function(){
            window.location.href = '/qoros/adm/admin-goods/index?activityId='+$("#activityId").val();
        });
    });

    function hideEdit(obj,inventory){
        $(obj).parent().parent().find('.edit').show();
        $(obj).parent().hide();
        $(obj).parent().parent().parent().find('#inventory').html(inventory);
    }
</script>
