<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <link href="/qoros/se7en/css/bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/font-awesome.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/se7en-font.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/isotope.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/fullcalendar.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/wizard.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/select2.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/datatables.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/datepicker.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/timepicker.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/bootstrap-switch.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/daterange-picker.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/typeahead.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/summernote.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/pygments.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/style.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/supplement.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/qoros/se7en/css/color/gray.css" media="all" rel="alternate stylesheet" title="gray-theme" type="text/css" />


    <script src="/qoros/se7en/js/jquery.min.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/jquery-ui.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/jquery.bootstrap.wizard.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/fullcalendar.min.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/excanvas.min.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/select2.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/jquery.inputmask.min.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/jquery.validate.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/bootstrap-fileupload.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/bootstrap-datepicker.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/bootstrap-timepicker.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/bootstrap-switch.min.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/typeahead.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/daterange-picker.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/date.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/main.js" type="text/javascript"></script>
    <script src="/qoros/se7en/js/respond.js" type="text/javascript"></script>
    <script src="/qoros/js/base.js" type="text/javascript"></script>
    <script src="/qoros/js/jquery.form.js" type="text/javascript"></script>
</head>
<body>

<div class="modal-shiftfix">
    <?php echo $this->partial('admin/top');?>
    <?php echo $this->partial('admin/alert');?>
    <?php echo $this->content; ?>
    <?php echo $this->partial('admin/modal');?>
    <div id="lodding" style="background-color: #000000;opacity: 0.6;z-index: 999999;width: 100%;height: 100%;position:absolute;left: 0;top: 0;display: none;"></div>
    <?php echo $this->partial('admin/bottom'); ?>
    <?php echo $this->inlineScript(); ?>
</div>

</body>
</html>
