<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="font-size: 58.59375px;">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0,user-scalable=no" >
    <meta content="yes" name="apple-mobile-web-app-capable">
    <title>用户登陆</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">

    <link href="/test_qoros/se7en/css/bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/test_qoros/se7en/css/font-awesome.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/test_qoros/se7en/css/se7en-font.css" media="all" rel="stylesheet" type="text/css" />
    <link href="/test_qoros/se7en/css/style.css" media="all" rel="stylesheet" type="text/css" />

    <script src="/test_qoros/se7en/js/jquery.min.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/jquery-ui.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/jquery.bootstrap.wizard.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/fullcalendar.min.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/excanvas.min.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/select2.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/jquery.inputmask.min.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/jquery.validate.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/bootstrap-fileupload.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/bootstrap-datepicker.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/bootstrap-timepicker.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/bootstrap-switch.min.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/typeahead.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/daterange-picker.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/date.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/main.js" type="text/javascript"></script>
    <script src="/test_qoros/se7en/js/respond.js" type="text/javascript"></script>
    <script src="/test_qoros/js/base.js" type="text/javascript"></script>
    <script src="/test_qoros/js/jquery.form.js" type="text/javascript"></script>


</head>

    <body class="login2" style="text-align: center;">
        <?php echo $this->partial('admin/alert');?>
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript(); ?>
        <?php echo $this->partial('admin/bottom'); ?>
    </body>
</html>
