<body class="fourofour">
<!-- Login Screen -->
<div class="fourofour-container">
    <h1>
        404
    </h1>
    <h2>
        <p class="error-404">该页面不存在</p>
    </h2>
</div>
<!-- End Login Screen -->
</body>

<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/image/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/style.css');?>