<div class="modal fade" id="site-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-hidden="true" class="close" data-dismiss="modal" type="button">&times;</button>
                <h4 class="modal-title" id="site-modal-title">
                </h4>
            </div>
            <div class="modal-body" id="site-modal-content">

            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal" type="button" id="site-model-ok">确定</button>
                <button class="btn btn-default-outline" data-dismiss="modal" type="button" id="site-model-cancel">取消</button>
            </div>
        </div>
    </div>
</div>
