<div class="login-wrapper">
    <div  style="height: 100px;"></div>
    <a></a>
    <form method="post">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="icon-phone"></i></span>
                <input class="form-control" name="mobile" placeholder="用户名/手机号" type="text">
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i class="icon-lock"></i></span>
                <input class="form-control" name="password" placeholder="密码" type="password">
            </div>
        </div>
        <div class="text-left">
            <label class="checkbox"></label>
        </div>
        <input class="btn btn-lg btn-primary btn-block" type="submit" value="登陆">
    </form>

</div>

