
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="font-size: 58.59375px;">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0,user-scalable=no" >
    <meta content="yes" name="apple-mobile-web-app-capable">
    <title><?php echo (isset($title)? $title:'观致汽车');?></title>

</head>

<body>
    <?php echo $this->content; ?>
    <?php echo $this->inlineScript(); ?>
</body>
</html>
